export const GET_BGAMES_SUCCESS = 'get_boardgames_success'
export const GET_BGAMES_FAILURE = 'get_boardgames_failure'
export const GET_MYLIST_SUCCESS = 'get_mylist_success'
export const GET_MYLIST_FAILURE = 'get_list_failure'
export const GET_BGAME_DETAIL_SUCCESS = 'get_detail_success'
export const GET_BGAME_DETAIL_FAILURE = 'get_detail_failure'
export const SET_GAME = 'set_game'